### ISSUE TITLE
Error when setting a value to 0

### ISSUE THREAD

**Issue by Joshua-F** [intellij-rust/intellij-toml#13]
Using the following shows an error when trying to set `start` to `0`.

```toml
[var]
start = 0
end = 1
```
![Error picture](http://i.imgur.com/6UMk8yF.png)
